#!C:\Users\Visiteur\Desktop\Julien\Privacy\13-GitHub Projects\Speech-Transcription\venvAudioProcessing\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
